### ISSUE TITLE
Cross-filtering not working with brush selection. 

### ISSUE THREAD

**Issue by MartinJuel** [deneb-viz/deneb#223]
Hi,

first of all. Thanks for developing Deneb. I enjoy using it so much! I came across this problem and don't know if it is a know limitation or not. Or if there already is a solution. 

**Issue: Cross filtering (Selection) data points**  

Purpose: Filter other visuals including native visuals on the page, based on the selection made in the Deneb visual.

**Problem**

When "Cross filtering (selection) data points" is enabled, the selected data when using mouse click-drag disappear when mouse-click is released. This does not happen when the "Cross filtering (selection) data points" is not enabled.

It is possible to select a single data point and filter other visuals, but the purpose is to select multiple data points at a time.

Example of issue:
https://drive.google.com/file/d/1tY04MNFfDJRGeHih69y662IzdhF2uPtA/view?usp=sharing

**Comment by dm-p** [comment]
Thanks for raising, and glad to hear you're enjoying the visual. 

This will need a lot of exploration to determine if it can be possible - Vega-Lite doesn't expose enough detail for an external tool like Deneb when using these selectors: just a start and end value; no field name of anything like that we can use to determine. This probably works fine internally, but not so much externally; Power BI does not support range or interval-based selection and would require us to 'collect' all individual data points to send to its selection manager for delegation. It also becomes problematic if we're, say, using it in a layer or facet that filters out data points, or groups by a particular category. Again, we're not able to get the detail we need here in an API-like way.

I have #176 in the backlog to do some work around determining the state in more detail & documenting functional gaps, as we may need to request some help from (or contribute to) Vega/Vega-Lite to expose more information that we can then use for handling this. I'll keep this issue on the backlog also, as I can use your workbook to assist me with any analysis (thanks for providing BTW).

**Comment by MartinJuel** [comment]
Thanks for the explanation. I didn't expect that there would be a simple solution, but I hope it gets resolved in the near future.

I can't share the data, but just want to share a use-case and what I have been working on. 

I'm working with a lot of disconected data sources. Both manual logs and IoT data. I'm using a bar-mark to show the state of an asset, and then point-marks to plot different types of events. This gives the end-user a visual reprentation of what is happening and when.  

Plotting all of this on a timeline using Deneb takes the analysis to a whole new level. No other visual in Power BI can provide this kind of insight. Being able to filter other visuals using the timeline would of course make this visual even more powerful. 

![image](https://user-images.githubusercontent.com/38399778/160392910-b1e48738-021b-4554-833b-88a6c5daa1d4.png)

**Comment by dm-p** [comment]
That's a great looking visual! 😃 

I've had a quick chance to view your workbook, and I just want to confirm your use case. This is how I interpret it:

* As a report developer & consumer
* I want the brush interaction to pass the highlighted range to Power BI's selection manager
* So that I can ensure that visuals external to mine reflect the current highlighted selection

I still don't have an ETA for when I can invest time in this, but I just want to be sure I understand for when I do (I estimate it will be a large piece of work and I only have so much free time available for development).

**Comment by MartinJuel** [comment]
thanks! 
Yes, that covers it very well.

That is fair. I will stay updated on the issue and find a workaround in the meantime:)
